[package]
name = "examples"
version = "0.1.0"
authors = ["Chris Ohk <utilforever@gmail.com>"]
edition = "2018"

[dependencies.mightmagic]
path = "../src"

[[bin]]
name = "mightmagic_console"
path = "mightmagic_console.rs" 